version: "3.9"
services: 
  app: 
    restart: on-failure
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - DATABASE_URL=mysql+pysql://root:root@db:3306/testdb
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=docker_compose
      - DB_HOST=db
      - DB_NAME=docker_compose
      - DB_USER=root
      - DB_PASS=password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: