from tkinter import *
from tkinter import ttk
n=Tk()
n.title("Student Registration Form")
n.geometry("700x500")
n.configure(bg="SlateBlue")
var1=StringVar()
var2=StringVar()
var3=StringVar()
var4=StringVar()
var5=StringVar()
var6=StringVar()

num=IntVar()

l1=Label(n,text="FIRST NAME",bg="#6a5acd",fg='White').grid(row=0,pady=10,sticky=W )
l2=Label(n,text="LAST NAME",bg="#6a5acd",fg='White').grid(row=1,pady=10,sticky=W )
l3=Label(n,text="DATE OF BIRTH",bg="#6a5acd",fg='White').grid(row=2,pady=10,sticky=W )
l4=Label(n,text="EMAIL ID",bg="#6a5acd",fg='White').grid(row=3,pady=10,sticky=W )
l5=Label(n,text="MOBILE NUMBER",bg="#6a5acd",fg='White').grid(row=4,pady=10,sticky=W )
l6=Label(n,text="GENDER",bg="#6a5acd",fg='White').grid(row=5,sticky=W )
l7=Label(n,text="ADDRESS",bg="#6a5acd",fg='White').grid(row=6,pady=10,sticky=W )
l9=Label(n,text="CITY",bg="#6a5acd",fg='White').grid(row=9,pady=10,sticky=W )
l10=Label(n,text="PINCODE",bg="#6a5acd",fg='White').grid(row=10,pady=10,sticky=W )
l11=Label(n,text="STATE",bg="#6a5acd",fg='White').grid(row=11,pady=10,sticky=W )
l12=Label(n,text="COUNTRY",bg="#6a5acd",fg='White').grid(row=12,pady=10,sticky=W )
l13=Label(n,text="HOBBIES",bg="#6a5acd",fg='White').grid(row=13,pady=10,sticky=W )
l14=Label(n,text="QUALIFICATION  ",bg="#6a5acd",fg='White').grid(row=15,pady=20,sticky=W )
l15=Label(n,text="COURSES\nAPPLIED FOR",bg="#6a5acd",fg='White').grid(row=21,pady=10,sticky=W )

e1=Entry(n,textvariable=var1).grid(row=0,padx=10,column=1,sticky=W )
e2=Entry(n,textvariable=var2).grid(row=1,padx=10,column=1,sticky=W )
e61=Radiobutton(n,text="Male",variable=num,value=1,bg='SlateBlue',fg='White',justify="left",selectcolor='dark grey').grid(row=5,column=1,sticky=W,padx=2)
e62=Radiobutton(n,text="Female",variable=num,value=2,bg='SlateBlue',fg='White',selectcolor='dark grey').grid(row=5,column=1,sticky=E)
e4=Entry(n,textvariable=var3).grid(row=3,padx=10,column=1,sticky=W )
e5=Entry(n,textvariable=var4).grid(row=4,padx=10,column=1,sticky=W )
e6=Entry(n,textvariable=var5).grid(row=6,padx=10,rowspan=3,sticky=W,column=1)
e7=Entry(n,textvariable=var6).grid(row=6,padx=10,ipady=20,column=1,sticky=W )

mon=StringVar()
num_day=StringVar()
yrs=StringVar()
day=ttk.Combobox(n,width=3,textvariable=num_day)
month=ttk.Combobox(n,width=9,textvariable=mon)
year=ttk.Combobox(n,width=8,textvariable=yrs)
day['values']=('Day:','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31')
day.grid(row=2,column=1,padx=1,sticky=W,ipadx=10)
day.current(0)
month['values']=('Month:','January','February','March','April','May','June','July','August','September','October','November','December')
month.grid(row=2,column=1,padx=1,sticky=E)
month.current(0)
year['values']=('Year:','1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022')
year.grid(row=2,column=2,padx=2,sticky=W)
year.current(0)

v=StringVar()
entry=Entry(n,textvariable=v).grid(row=14,column=2,sticky=W)
ch1=IntVar()
ch2=IntVar()
ch3=IntVar()
ch4=IntVar()
ch5=IntVar()
val1=StringVar()
val2=StringVar()
val3=StringVar()
val4=StringVar()
e9=Entry(n,textvariable=val1).grid(row=9,padx=10,column=1,sticky=W )
e10=Entry(n,textvariable=val2).grid(row=10,padx=10,column=1,sticky=W )
e11=Entry(n,textvariable=val3).grid(row=11,padx=10,column=1,sticky=W )
e12=Entry(n,textvariable=val4).grid(row=12,padx=10,column=1,sticky=W )
c1=Checkbutton(n,text='Drawing',onvalue=1,offvalue=0,bg='SlateBlue',fg='White',variable=ch1,selectcolor='dark grey').grid(row=13,column=1,sticky=W)
c2=Checkbutton(n,text='Singing',onvalue=1,offvalue=0,bg='SlateBlue',fg='White',variable=ch2,selectcolor='dark grey').grid(row=13,column=1,sticky=E)
c3=Checkbutton(n,text='Dancing',onvalue=1,offvalue=0,bg='SlateBlue',fg='White',variable=ch3,selectcolor='dark grey').grid(row=13,column=2,sticky=W)
c4=Checkbutton(n,text="Sketching",onvalue=1,offvalue=0,bg='SlateBlue',fg='White',variable=ch4,selectcolor='dark grey').grid(row=13,column=2,sticky=E)
c5=Checkbutton(n,text='Others',bg='SlateBlue',fg='White',onvalue=1,offvalue=0,variable=ch5,selectcolor='dark grey').grid(row=14,column=1,sticky=W)

l1=Label(n,text='SI.No.   Examination',bg='Slateblue',fg='White',anchor=CENTER).grid(row=15,column=1)
l3=Label(n,text='Board',bg='Slateblue',fg='White',anchor=CENTER).grid(row=15,column=2)
l4=Label(n,text='Percentage',bg='Slateblue',fg='White',anchor=CENTER).grid(row=15,column=3)
l5=Label(n,text='Year of Passing',bg='Slateblue',fg='White',anchor=CENTER).grid(row=15,column=4)

n1=Label(n,text='      1          Class X',bg='Slateblue',fg='White').grid(row=16,column=1,padx=3,sticky=W)
n2=Label(n,text='      2          Class XII',bg='Slateblue',fg='White').grid(row=17,column=1,padx=3,sticky=W)
n3=Label(n,text='      3          Graduation',bg='Slateblue',fg='White').grid(row=18,column=1,padx=3,sticky=W)
n4=Label(n,text='      4          Masters',bg='Slateblue',fg='White').grid(row=19,column=1,padx=3,sticky=W)

num1=StringVar()
num2=StringVar()
num3=StringVar()
num4=StringVar()
Entry(n,textvariable=num1,width=30).grid(row=16,padx=1,pady=1,column=2 )
Entry(n,textvariable=num2,width=30).grid(row=17,padx=1,pady=1,column=2 )
Entry(n,textvariable=num3,width=30).grid(row=18,padx=1,pady=1,column=2 )
Entry(n,textvariable=num4,width=30).grid(row=19,padx=1,pady=1,column=2 )

str1=StringVar()
str2=StringVar()
str3=StringVar()
str4=StringVar()
Entry(n,textvariable=str1,width=30).grid(row=16,padx=1,pady=1,column=3 )
Entry(n,textvariable=str2,width=30).grid(row=17,padx=1,pady=1,column=3 )
Entry(n,textvariable=str3,width=30).grid(row=18,padx=1,pady=1,column=3 )
Entry(n,textvariable=str4,width=30).grid(row=19,padx=1,pady=1,column=3 )

s1=StringVar()
s2=StringVar()
s3=StringVar()
s4=StringVar()
Entry(n,textvariable=s1,width=30).grid(row=16,padx=1,pady=1,column=4 )
Entry(n,textvariable=s2,width=30).grid(row=17,padx=1,pady=1,column=4 )
Entry(n,textvariable=s3,width=30).grid(row=18,padx=1,pady=1,column=4 )
Entry(n,textvariable=s4,width=30).grid(row=19,padx=1,pady=1,column=4 )

button=IntVar()
b1=Radiobutton(n,text="BCA",variable=button,value=1,bg='SlateBlue',fg='White',justify="left",selectcolor='dark grey').grid(row=21,column=1,sticky=W)
b2=Radiobutton(n,text="B.Com",variable=button,value=2,bg='SlateBlue',fg='White',selectcolor='dark grey').grid(row=21,column=1,sticky=E)
b3=Radiobutton(n,text="BCA",variable=button,value=3,bg='SlateBlue',fg='White',justify="left",selectcolor='dark grey').grid(row=21,column=2,sticky=W)
b4=Radiobutton(n,text="B.Com",variable=button,value=4,bg='SlateBlue',fg='White',selectcolor='dark grey').grid(row=21,column=2,sticky=E)
Label(n,text='(max 30 characters a-z and A-Z)',bg="#6a5acd",fg='White').grid(row=11,column=2,sticky=W,pady=10)


Label(n,text='(max 30 characters a-z and A-Z)',bg="#6a5acd",fg='White').grid(row=0,pady=10,sticky=W,column=2)
Label(n,text='(max 30 characters a-z and A-Z)',bg="#6a5acd",fg='White').grid(row=1,pady=10,sticky=W,column=2)
Label(n,text='(10 digit number)',bg="#6a5acd",fg='White').grid(row=4,pady=10,sticky=W,column=2)
Label(n,text='(max 30 characters a-z and A-Z)',bg="#6a5acd",fg='White').grid(row=9,pady=10,sticky=W,column=2)
Label(n,text='(10 digit number)',bg="#6a5acd",fg='White').grid(row=10,pady=10,sticky=W,column=2)
Label(n,text='(10 char max)',bg="#6a5acd",fg='White',anchor=CENTER).grid(row=20,column=2)
Label(n,text='(upto 2 decimal)',bg="#6a5acd",fg='White',anchor=CENTER).grid(row=20,column=3)

submit=Button(n,text="Submit",command=n.destroy).grid(row=22,column=2,sticky=W,padx=2)
reset=Button(n,text="Reset",command=n.destroy).grid(row=22,column=2,sticky=E,padx=2)

n.mainloop()