from tkinter import*
root=Tk()
root.geometry("300x500")
root.title("Student")
Label(root,text="Regno : ").grid(row=0)
Label(root,text="Name : ").grid(row=1)
Label(root,text="Dept : ").grid(row=2)
Label(root,text="Gender : ").grid(row=3)
Label(root,text="Age : ").grid(row=4)
e1=Entry(root)
e2=Entry(root)
e3=Entry(root,text="CSE")
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
e3.grid(row=2,column=1)
v=StringVar()
# v1=StringVar()
Radiobutton(root,text="Male",variable=v,value="1").grid(row=3,column=1)
Radiobutton(root,text="FeMale").grid(row=3,column=2)
w=Spinbox(root,from_=0,to=10)
w.grid(row=4,column=1)
n1=Button(root,text="Insert")
n2=Button(root,text="Update")
n3=Button(root,text="Delete")
n4=Button(root,text="Select")
n1.grid(row=5)
n2.grid(row=5,column=1)
n3.grid(row=6,column=0)
n4.grid(row=6,column=1)
Label(root,text="amount").grid(row=7)
s1=Scale(root,variable=v,from_=0,to=100,orient=HORIZONTAL)
s1.grid(row=7,column=1)
root.mainloop()
